### ISSUE TITLE
ShadowForce - No slippage control when user deposits

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-gmx-judging#122]
ShadowForce

high

# No slippage control when user deposits

## Summary
There is no slippage control when user is depositing
## Vulnerability Detail
Slippage control is used to ensure the user receives a token amount that he expected to receive, with such slippage controls, a user may expect to receive 100 of a certain token and only recieve 50.

Lack of slippage control is evident in this protocol
```solidity
      uint256 supply = MarketUtils.getMarketTokenSupply(MarketToken(payable(_params.market.marketToken)));

        if (_params.priceImpactUsd > 0) {
            // when there is a positive price impact factor,
            // tokens from the swap impact pool are used to mint additional market tokens for the user
            // for example, if 50,000 USDC is deposited and there is a positive price impact
            // an additional 0.005 ETH may be used to mint market tokens
            // the swap impact pool is decreased by the used amount
            //
            // priceImpactUsd is calculated based on pricing assuming only depositAmount of tokenIn
            // was added to the pool
            // since impactAmount of tokenOut is added to the pool here, the calculation of
            // the tokenInPrice would not be entirely accurate
            int256 positiveImpactAmount = MarketUtils.applySwapImpactWithCap(
                params.dataStore,
                params.eventEmitter,
                _params.market.marketToken,
                _params.tokenOut,
                _params.tokenOutPrice,
                _params.priceImpactUsd
            );

            // calculate the usd amount using positiveImpactAmount since it may
            // be capped by the max available amount in the impact pool
            mintAmount += MarketUtils.usdToMarketTokenAmount(
                positiveImpactAmount.toUint256() * _params.tokenOutPrice.min,
                poolValue,
                supply
            );
```
The code snippet shown above calls into the snippet show below.

```solidity
   // @dev convert a USD value to number of market tokens
    // @param usdValue the input USD value
    // @param poolValue the value of the pool
    // @param supply the supply of market tokens
    // @return the number of market tokens
    function usdToMarketTokenAmount(
        uint256 usdValue,
        uint256 poolValue,
        uint256 supply
    ) internal pure returns (uint256) {
        if (supply == 0 || poolValue == 0) {
            return Precision.floatToWei(usdValue);
        }

        // round market tokens down
        return supply * usdValue / poolValue;
    }
```
From the snippets of code i have shown, let us assume a user is about to make a deposit and expects to recieve 100 of a token. At the same time the poolValue and supply drastically change because of a whale who either deposited or withdrew.

The user who expected to get 100 tokens might only get 90, and because there is no slippage control, there is no way for the protocol to mitigate this risk.
## Impact
The lack of slippage control may cause an oblivious user to recieve alot less tokens than he expected. Leading to loss of funds and loss of trust in the protocol.
## Code Snippet
https://github.com/gmx-io/gmx-synthetics/blob/91af13f93ee64e8cb50c37e4e8084037cbde15a7/contracts/deposit/ExecuteDepositUtils.sol#L295-L323

https://github.com/gmx-io/gmx-synthetics/blob/91af13f93ee64e8cb50c37e4e8084037cbde15a7/contracts/market/MarketUtils.sol#L1918-L1934
## Tool used

Manual Review

## Recommendation
I recommend the protocol add proper slippage controls

**Comment by Jiaren-tang** [comment]
Escalate to 10 USDC. I think this one should be rated as high, or at least medium severity, because Sherlock has previously classified other slippage-related issues as high severity. Between the user's submission of a deposit transaction and the time when the transaction is processed, the user has no control over the value of the supply, which is derived from the following 

```solidity
uint256 supply = MarketUtils.getMarketTokenSupply(MarketToken(payable(_params.market.marketToken)));
```

It is possible that before the user makes the deposit, the supply could be deflated and burned by a large transaction, and because of the following code:

```solidity
   // @dev convert a USD value to number of market tokens
    // @param usdValue the input USD value
    // @param poolValue the value of the pool
    // @param supply the supply of market tokens
    // @return the number of market tokens
    function usdToMarketTokenAmount(
        uint256 usdValue,
        uint256 poolValue,
        uint256 supply
    ) internal pure returns (uint256) {
        if (supply == 0 || poolValue == 0) {
            return Precision.floatToWei(usdValue);
        }

        // round market tokens down
        return supply * usdValue / poolValue;
    }
```

the user could end up receiving a much smaller share than expected.

Alternatively, the poolValue could be inflated significantly before the user's deposit transaction is processed, resulting in the user receiving an infinitely small share due to the calculation supply * usdValue / poolValue.

Since the deposit function is similar to the addLiquidity function in Uniswap, it is necessary to control slippage to ensure that the user does not receive a suboptimal share due to the order of transactions.

Reference: https://docs.uniswap.org/contracts/v2/reference/smart-contracts/router-02#addliquidity"

**Comment by IllIllI000** [comment]
There is [slippage control](https://github.com/gmx-io/gmx-synthetics/blob/91af13f93ee64e8cb50c37e4e8084037cbde15a7/contracts/deposit/ExecuteDepositUtils.sol#L224-L226) - Invalid

**Comment by hrishibhat** [comment]
Escalation rejected

Not a valid issue
As shown in the above comment, Slippage control exists.
