### ISSUE TITLE
IllIllI - Market orders lose submitted prices if markets are temporarily disabled

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-gmx-judging#147]
IllIllI

medium

# Market orders lose submitted prices if markets are temporarily disabled

## Summary

Limit orders become frozen if a required market for the order (the order execution itself, or the swap afterwards) is temporarily disabled by admins. Market orders are instead canceled

## Vulnerability Detail

A keeper may happen to disable a market just as market-moving news is released, and anyone with market orders will potentially have them canceled until the keeper re-enables the execution of orders for the market, and the user is able to resubmit.

## Impact

While the order execution is temporarily disabled (but potentially not order submission), the market may gap a lot, and the user may be subject to an unexpected liquidation, even though they submitted a market exit order, because the order is canceled rather than held with the submitted price.

## Code Snippet

Market orders are canceled, whereas limit orders revert, which means they can be retried by the keeper later:

```solidity
// File: gmx-synthetics/contracts/exchange/OrderHandler.sol : OrderHandler._handleOrderError()   #1

236            if (isMarketOrder) {
237 @>             OrderUtils.cancelOrder(
238                    dataStore,
239                    eventEmitter,
240                    orderVault,
241                    key,
242                    msg.sender,
243                    startingGas,
244                    reason,
245                    reasonBytes
246                );
247            } else {
248                if (
249 @>                 errorSelector == FeatureUtils.DisabledFeature.selector ||
250                    errorSelector == PositionUtils.EmptyPosition.selector ||
251                    errorSelector == BaseOrderUtils.InvalidOrderPrices.selector
252                ) {
253                    ErrorUtils.revertWithCustomError(reasonBytes);
254:               }
```
https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/exchange/OrderHandler.sol#L227-L256

## Tool used

Manual Review

## Recommendation

Market orders should not be canceled, and should instead revert like limit orders, so that they can be retried when things are re-enabled

**Comment by IllIllI000** [comment]
Duplicate of #124

**Comment by IllIllI000** [comment]
Escalate for 11 USDC

**Comment by IllIllI000** [comment]
I messed up the tagging - Valid duplicate Medium

**Comment by hrishibhat** [comment]
Escalation accepted

Valid duplicate of #124
