### ISSUE TITLE
IllIllI - Disabling of markets can be front-run for risk-free trades

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-gmx-judging#148]
IllIllI

medium

# Disabling of markets can be front-run for risk-free trades

## Summary

Disabling of markets can be front-run for risk-free trades

## Vulnerability Detail

If a user with a large position open sees that a market's executions are being disabled (e.g. a scheduled maintenance window), the user can front-run it with a limit order to exit the position. If they happen in the same block, there is no way for an order keeper to execute the order before the disable happens. Up until the market is re-enabled, the user has a free option to cancel the order at any time if they see that the position loses any money.

## Impact

The trader is able to get a free look into the future and decide whether to let the position run, or to exit. This is more advantageous than having a stoploss, because with a stop, if the price later recovers, then you've missed out on the recovery. In this scenario, the trader can see all subsequent history, and then make a decision. If the trader makes a gain, this is necessarily at the expense of another user.

## Code Snippet

Orders while the feature is disabled, revert if the keeper tries to execute them, which means they're executed later after the market is re-enabled:

```solidity
// File: gmx-synthetics/contracts/exchange/OrderHandler.sol : OrderHandler._handleOrderError()   #1

248                if (
249 @>                 errorSelector == FeatureUtils.DisabledFeature.selector ||
250                    errorSelector == PositionUtils.EmptyPosition.selector ||
251                    errorSelector == BaseOrderUtils.InvalidOrderPrices.selector
252                ) {
253                    ErrorUtils.revertWithCustomError(reasonBytes);
254                }
```
https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/exchange/OrderHandler.sol#L248-L254

## Tool used

Manual Review

## Recommendation

For cases where the order currently reverts with `DisabledFeature`, create another order state, similar to frozen, where the order is marked with the current block number to indicated that it _would_ have been executed at that block, but otherwise remains paused, so that later it can be re-executed by a keeper once the market is re-enabled. Once an order reaches this new state, it shouldn't be cancellable.

**Comment by xvi10** [comment]
orders should only be disabled in an emergency, possibly creation of orders should be disabled during this time as well

**Comment by IllIllI000** [comment]
@xvi10, I believe your `possibly` indicates that this finding has given you new information that you are able to work around via non-code fixes, is that right? Trying to confirm so that Sherlock can decide whether this type of issue is rewardable or not

**Comment by xvi10** [comment]
i'm not sure what would what be an accurate way to term it, this report would be a reminder to update the documentation that order creation should be disabled if order execution is disabled, so there is no code change but there is documentation improvement

**Comment by IllIllI000** [comment]
@hrishibhat not sure whether the provided answer falls into the rewarded category or not

**Comment by JeffCX** [comment]
Escalate for 10 UDSC. Based on the sponsor's comment, it appears that no code change is needed, and historically, Sherlock has not rewarded documentation updates.

According to Sherlock's judging guidelines:

Medium: There is a viable scenario (even if unlikely) that could cause the protocol to enter a state where a material amount of funds can be lost. The attack path is possible with assumptions that either mimic on-chain conditions or reflect conditions that have a reasonable chance of becoming true in the future. The more expensive the attack is for an attacker, the less likely it will be included as a Medium (holding all other factors constant). The vulnerability must be something that is not considered an acceptable risk by a reasonable protocol team.

However, the fact that no code change is required suggests that this may be considered an acceptable risk by a reasonable protocol team. Therefore, I do not believe this issue meets the criteria for a Medium severity rating.

**Comment by IllIllI000** [comment]
This issue was not properly escalated

**Comment by hrishibhat** [comment]
Given that this is about ensuring these features are set by the OrderKeepers during an emergency, 
Considering this as low.
