### ISSUE TITLE
IllIllI - No way to reimburse funding fees from an insurance fund

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-gmx-judging#162]
IllIllI

medium

# No way to reimburse funding fees from an insurance fund

## Summary

In cases where a liquidation results in there not being enough collateral to cover the funding fee, the code comments say that the pool will be topped up via an insurance fund.

## Vulnerability Detail

There is no way to reimburse funding fees from an insurance fund, because the pool value is not based on the balance of tokens, but on separate tracking of specific token amounts. Tokens manually sent without calling [applyDeltaToPoolAmount()](https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/market/MarketUtils.sol#L666), will have no effect on the pool balance. 

## Impact

When such a shortfall occurs, the pool is not paused in any way, so users that sell their market tokens will do so without being paid what they're owed, an users that buy the tokens will purchase them at a discount until the pool is upgraded, and the fees are properly distributed.

## Code Snippet
There is no code that accomplishes the action described by the comment:
```solidity
// File: gmx-synthetics/contracts/position/DecreasePositionCollateralUtils.sol : DecreasePositionCollateralUtils.getLiquidationValues()   #1

333            if (fees.funding.fundingFeeAmount > params.position.collateralAmount()) {
334                values.pnlAmountForPool = 0;
335 @>             // the case where this is insufficient collateral to pay funding fees
336                // should be rare, and the difference should be small
337                // in case it happens, the pool should be topped up with the required amount using
338                // an insurance fund or similar mechanism
339                PositionEventUtils.emitInsufficientFundingFeePayment(
340                    params.contracts.eventEmitter,
341                    params.market.marketToken,
342                    params.position.collateralToken(),
343                    fees.funding.fundingFeeAmount,
344:                   params.position.collateralAmount()
```
https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/position/DecreasePositionCollateralUtils.sol#L333-L344

## Tool used

Manual Review

## Recommendation

Add a function to sweep latent pool tokens into the pool balance, only callable by a keeper

**Comment by IllIllI000** [comment]
@xvi10 I agree that the funding fees portion can be topped up, but isn’t the pool supposed to get the collateral? Unlike the else block, it’s not being accounted for even if it’s non-zero but still less than the funding fee, and that part can’t be topped up

**Comment by xvi10** [comment]
I don't think the poolAmount needs to be increased, for example:

1. 1000 USDC has been deposited into a market's pool, poolAmount: 1000 USDC
2. user A has 200 USDC of collateral in their position, user A owes 150 USDC of funding fees
3. user B has 500 USDC of collateral and has earned 150 USDC of funding fees
4. Total USDC in the MarketToken: 1000 + 200 + 500 => 1700

will assume all other fees are zero for simplicity

if all the positions are closed now:

1. user A receives 50 USDC, 150 USDC is left in the MarketToken, 1700 - 50 => 1650
2. user B receives 500 USDC and claims 150 USDC of funding fees, 1650 - 500 - 150 => 1000
3. there is 1000 USDC remaining in the MarketToken 

if user A is in a loss of 52 USDC and is liquidated and all positions are closed:

1. user A receives 0 USDC
2. user B receives 500 USDC and claims 150 USDC of funding fees, 1700 - 500 - 150 => 1050
3. The poolAmount is increased by 200 - 150 => 50
4. there is 1050 USDC remaining in the MarketToken 

if user A owes 210 USDC of funding fees to user B and user A is liquidated and all positions are closed:

1. user A receives 0 USDC
2. user B receives 500 USDC and claims 210 USDC of funding fees, 1700 - 500 - 210 => 990
3. The poolAmount is not increased, poolAmount is 1000
4. there is 990 USDC remaining in the MarketToken 

so if the USDC balance of the MarketToken is increased back to 1000 by a direct sending of USDC into the MarketToken, that should resolve the issue

**Comment by IllIllI000** [comment]
Thanks, that example is very clear. @hrishibhat Agree with sponsor – invalid
