### ISSUE TITLE
IllIllI - WNT withdrawals waste extra gas to send back excess execution fees and gas refunds

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-gmx-judging#172]
IllIllI

medium

# WNT withdrawals waste extra gas to send back excess execution fees and gas refunds

## Summary

WNT withdrawals waste extra gas to send back excess execution fees and gas refunds

## Vulnerability Detail

When the withdrawal is of a wrapped native token, the transfer of the withdrawal of the token is executed, then a separate transfer is done for the excess execution fees.

This is in contrast to the deposit case, where a single transfer from the user is used to cover both the input token as well as the execution fees, in the case where they both are WNT.

## Impact

User pays extra gas for a transfer that they wouldn't have had to do if they weren't forced to use GMX's. This will be especially frustrating when the user cancels the order themselves, and there is no keeper involved.

## Code Snippet

Deposited amounts are transferred back to the account, and the execution fee refund is handled separately:
```solidity
// File: gmx-synthetics/contracts/deposit/DepositUtils.sol : DepositUtils.cancelDeposit()   #1

162            if (deposit.initialLongTokenAmount() > 0) {
163 @>             depositVault.transferOut(
164                    deposit.initialLongToken(),
165                    deposit.account(),
166                    deposit.initialLongTokenAmount(),
167                    deposit.shouldUnwrapNativeToken()
168                );
169            }
170    
171            if (deposit.initialShortTokenAmount() > 0) {
172 @>             depositVault.transferOut(
173                    deposit.initialShortToken(),
174                    deposit.account(),
175                    deposit.initialShortTokenAmount(),
176                    deposit.shouldUnwrapNativeToken()
177                );
178            }
...
186            GasUtils.payExecutionFee(
187                dataStore,
188                depositVault,
189                deposit.executionFee(),
190                startingGas,
191                keeper,
192 @>             deposit.account()
193            );
194:       }
```
https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/deposit/DepositUtils.sol#L170-L190

If the user was the one that canceled the order, the order's account is the keeper address, so that is yet another transfer.

The other order types that send back tokens have the same issue.

## Tool used

Manual Review

## Recommendation

Transfer the execution refunds as a part of the vault transfers if they're both WNT

**Comment by xvi10** [comment]
this is a valid gas optimization suggestion, marked as disputed as we believe that gas optimization is not a medium issue

**Comment by IllIllI000** [comment]
@hrishibhat sherlock does not reward gas – invalid
