### ISSUE TITLE
IllIllI - Config value changes apply retro-actively to already-submitted orders

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-gmx-judging#178]
IllIllI

medium

# Config value changes apply retro-actively to already-submitted orders

## Summary

Config value changes apply retro-actively to already-submitted orders. At order submission time, there's no way to calculate an exact slippage output amount, to avoid being sandwiched, because config values may change between order acceptance, and keeper execution.

## Vulnerability Detail

Config values are changeable at any time by the config keepers, and since order submission is separate from order execution (can be an hour later), values affecting execution price may change.

## Impact

A user using automation and trying to exit their position with minimal slippage, may have their order canceled, and will have to resubmit at worse prices, meaning that there is no safe way to exit positions while using slippage protection.

## Code Snippet

The price impact factors are changeable at any time by the config keepers, and orders use the current values, not the values at execution time:
```solidity
// File: gmx-synthetics/contracts/config/Config.sol : Config._initAllowedBaseKeys()   #1

239            allowedBaseKeys[Keys.THRESHOLD_POSITION_IMPACT_FACTOR_FOR_VIRTUAL_INVENTORY] = true;
240            allowedBaseKeys[Keys.THRESHOLD_SWAP_IMPACT_FACTOR_FOR_VIRTUAL_INVENTORY] = true;
241    
242            allowedBaseKeys[Keys.POSITION_IMPACT_FACTOR] = true;
243            allowedBaseKeys[Keys.POSITION_IMPACT_EXPONENT_FACTOR] = true;
244            allowedBaseKeys[Keys.MAX_POSITION_IMPACT_FACTOR] = true;
245            allowedBaseKeys[Keys.POSITION_FEE_FACTOR] = true;
246    
247            allowedBaseKeys[Keys.SWAP_IMPACT_FACTOR] = true;
248            allowedBaseKeys[Keys.SWAP_IMPACT_EXPONENT_FACTOR] = true;
249:           allowedBaseKeys[Keys.SWAP_FEE_FACTOR] = true;
```
https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/config/Config.sol#L235-L255

## Tool used

Manual Review

## Recommendation

Checkpoint old factor values with timestamps, and use the factor that was in effect when the order was submitted

**Comment by xvi10** [comment]
the impact factors may change due to market conditions, orders should be executed based on the latest impact factors
