### ISSUE TITLE
IllIllI - Oracle type not checked

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-gmx-judging#180]
IllIllI

medium

# Oracle type not checked

## Summary

Each signing oracle's prices are tagged with an oracle type, which is included in the signature, to ensure that the order keeper cannot use prices from an oracle that is not supported for that market at that time, i.e. the price is one of the offline oracle prices, or one of the historical Chainlink prices also served by the oracle price archive.

## Vulnerability Detail

While the type is in the signature, the type is not checked against the market, so for example if there is a difference in price between the prices of two sets of oracles of different types, the signer can use whichever is more advantageous to it.

## Impact

Users won't get consistent prices, and order keepers are free to use whichever oracle prices they wish, at the expense of exchange customers

## Code Snippet
The oracle type is fetched for the purposes of [hashing](https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/oracle/OracleUtils.sol#L263), but is otherwise unused:
```solidity
// File: gmx-synthetics/contracts/oracle/Oracle.sol : Oracle._setPrices()   #1

469                cache.info.token = params.tokens[i];
470                cache.info.precision = 10 ** OracleUtils.getUncompactedDecimal(params.compactedDecimals, i);
471 @>             cache.info.tokenOracleType = dataStore.getBytes32(Keys.oracleTypeKey(cache.info.token));
472    
473                cache.minPrices = new uint256[](signers.length);
474                cache.maxPrices = new uint256[](signers.length);
475    
476                for (uint256 j = 0; j < signers.length; j++) {
477                    cache.priceIndex = i * signers.length + j;
478                    cache.minPrices[j] = OracleUtils.getUncompactedPrice(params.compactedMinPrices, cache.priceIndex);
479                    cache.maxPrices[j] = OracleUtils.getUncompactedPrice(params.compactedMaxPrices, cache.priceIndex);
480    
481:                   if (j == 0) { continue; }
```
https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/oracle/Oracle.sol#L461-L481

## Tool used

Manual Review

## Recommendation

Reject the oracle price if the type matches a market/token that requires a Chainlink oracle price or some other incorrect value, rather than a signed oracle price type at that time.

**Comment by xvi10** [comment]
the oracle type is set using the Config contract, order keepers must use the oracle type that was configured, all markets use the same oracle type for a single token
