### ISSUE TITLE
IllIllI - Oracle prices may be forced to be excluded

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-gmx-judging#181]
IllIllI

medium

# Oracle prices may be forced to be excluded

## Summary

In order to come up with a fair price for orders submitted in the past, and being currently executed by order keepers, the GMX code relies on signed oracle prices from oracle archive infrastructure. These prices include a min (bid) and a max (ask), and the GMX DEX gets these prices from multiple exchanges to source the best price. The best price is chosen as the median price, and the algorithm for finding this median is broken.

## Vulnerability Detail

The median-finding code relies on the input prices to be sorted, and the code that verifies that things are sorted assumes that if all of the bid prices are sorted, then the ask prices must also be in order, which is not the case.

## Impact

Some combinations of oracle prices won't be usable, which means either orders won't be able to be executed, or the median calculation will exclude arbitrary exchanges, leading to unreliable prices. In both cases, a bad price means someone gets the bad price when executing the trade, and they'll lose money. If the number of usable prices ends up being below [`MIN_ORACLE_PRICES`](https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/data/Keys.sol#L86) then the order will be unexecutable by the order keepers until it expires.

## Code Snippet
The prices inspected by signer (can be thought of as which exchange's price is being reported) and the first check is that the `minPrices` (bids) are sorted in ascending order, and then the `maxPrices` (asks) required to be sorted, and because the original signer order for the min prices is the same order being checked for the maxes, it's possible for the requirement not to be satisfied:
```solidity
// File: gmx-synthetics/contracts/oracle/Oracle.sol : Oracle._setPrices()   #1

476 @>             for (uint256 j = 0; j < signers.length; j++) {
477                    cache.priceIndex = i * signers.length + j;
478                    cache.minPrices[j] = OracleUtils.getUncompactedPrice(params.compactedMinPrices, cache.priceIndex);
479                    cache.maxPrices[j] = OracleUtils.getUncompactedPrice(params.compactedMaxPrices, cache.priceIndex);
480    
481                    if (j == 0) { continue; }
482    
483                    // validate that minPrices are sorted in ascending order
484 @>                 if (cache.minPrices[j - 1] > cache.minPrices[j]) {
485                        revert MinPricesNotSorted(cache.info.token, cache.minPrices[j], cache.minPrices[j - 1]);
486                    }
487    
488                    // validate that maxPrices are sorted in ascending order
489 @>                 if (cache.maxPrices[j - 1] > cache.maxPrices[j]) {
490                        revert MaxPricesNotSorted(cache.info.token, cache.maxPrices[j], cache.maxPrices[j - 1]);
491                    }
492:               }
```
https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/oracle/Oracle.sol#L474-L496

For example, assume signer0 is signing prices for Binance which is at bid/ask 90/110, and signer1 is signing for Kraken which is at 99/100. If signer0's prices come first, a min of 90 is less than a min of 99, so the first check passes, but 110 is not less than 100, so the prices are considered invalid. The opposite order will also fail, so both prices can't be used at the same time.

## Tool used

Manual Review

## Recommendation

Use separate signer orderings for checking min and max prices

**Comment by xvi10** [comment]
the validation of the min / max price ordering is in one loop and the validation of signatures is in a separate loop

for the given example,

min prices should be: 90, 99
max prices should be: 100, 110

for signature validation minPriceIndex and maxPriceIndex are used to reference the prices

for signer0, minPriceIndex should be 0, maxPriceIndex should be 1
for signer1, minPriceIndex should be 1, maxPriceIndex should be 0

as a side note, a validation should be added to check that all prices provided in the min and max price array are signed, to avoid a case where all oracle keepers had signed equal prices and an order keeper can distort the median by filling the array with unsigned prices

**Comment by IllIllI000** [comment]
@xvi10 I understand that there are two separate loops, but the area I’m pointing to is the min/max loop, not the signature loop. Lines 484 and 489 are in the same loop, so doesn’t that mean that both the min and max must be monotonically increasing across all signers?

**Comment by xvi10** [comment]
the values in minPrices and maxPrices must be in increasing order

the minPrices and maxPrices ordering does not need to relate to the ordering or indexes of signers

if we have:

minPrices: 90, 99
maxPrices: 100, 110
signers: signer0, signer1

it does not necessarily mean that signer0 signed [90, 100] and signer1 signed [99, 110]

which prices were signed by which signer is indicated by the minPriceIndex, maxPriceIndex specified for each signer in compactedMinPricesIndexes and compactedMaxPricesIndexes

**Comment by IllIllI000** [comment]
@xvi10 I believe this test shows the issue I’ve been describing – can you let me know if I’m missing something? As in my example above, signer0 has 90/110, and signer1 has 99/100 – is there a different way to specify this? If confirmed, I think this should be marked as High rather than Medium, since it’s likely to occur frequently: 

```diff
diff --git a/gmx-synthetics/test/oracle/Oracle.ts b/gmx-synthetics/test/oracle/Oracle.ts
index bede1be..8ee7178 100644
--- a/gmx-synthetics/test/oracle/Oracle.ts
+++ b/gmx-synthetics/test/oracle/Oracle.ts
@@ -298,8 +298,8 @@ describe("Oracle", () => {
     ).to.be.revertedWithCustomError(oracle, "InvalidSignature");
 
     signerInfo = getSignerInfo([0, 1, 2, 3, 4, 7, 9]);
-    minPrices = [4990, 4991, 4995, 5000, 5001, 5005, 5007];
-    maxPrices = [4990, 4991, 4995, 5010, 5011, 5015, 5017];
+    minPrices = [90, 99, 4995, 5000, 5001, 5005, 5007];
+    maxPrices = [110, 100, 4995, 5010, 5011, 5015, 5017];
     signatures = await signPrices({
       signers: [signer0, signer1, signer2, signer3, signer4, signer7, signer9],
       salt: oracleSalt,
@@ -325,7 +325,7 @@ describe("Oracle", () => {
       compactedMinPrices: getCompactedPrices(minPrices),
       compactedMinPricesIndexes: getCompactedPriceIndexes([0, 1, 2, 3, 4, 5, 6]),
       compactedMaxPrices: getCompactedPrices(maxPrices),
-      compactedMaxPricesIndexes: getCompactedPriceIndexes([0, 1, 2, 3, 4, 5, 6]),
+      compactedMaxPricesIndexes: getCompactedPriceIndexes([1, 0, 2, 3, 4, 5, 6]),
       signatures,
     });
 
```

```shell
$ npx hardhat test test/oracle/Oracle.ts
  Oracle
    ✔ inits
    1) setPrices
oracle.withOraclePrices tx0 428810
oracle.withOraclePrices tx1 492092
oracle.withOraclePrices tx2 638639
    ✔ withOraclePrices (1532ms)


  2 passing (22s)
  1 failing

  1) Oracle
       setPrices:
     Error: VM Exception while processing transaction: reverted with custom error 'MaxPricesNotSorted("0x99bbA657f2BbC93c02D617f8bA121cB8Fc104Acf", 100, 110)'
    at Oracle.getLatestPrice (contracts/oracle/Oracle.sol:355)
    at Oracle.setPrices (contracts/oracle/Oracle.sol:253)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:533:9)
    at processTimers (node:internal/timers:507:7)
    at async HardhatNode._mineBlockWithPendingTxs (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1805:23)
    at async HardhatNode.mineBlock (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:494:16)
    at async EthModule._sendTransactionAndReturnHash (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1522:18)
```

**Comment by xvi10** [comment]
for the example, signer0 has 90/110, and signer1 has 99/100, the parameters should be:

signers: [signer0, signer1, signer2, signer3, signer4, signer7, signer9]

minPrices = [90, 99, 4995, 5000, 5001, 5005, 5007];
maxPrices = [100, 110, 4995, 5010, 5011, 5015, 5017];

compactedMinPricesIndexes: getCompactedPriceIndexes([0, 1, 2, 3, 4, 5, 6])
compactedMaxPricesIndexes: getCompactedPriceIndexes([1, 0, 2, 3, 4, 5, 6])

**Comment by IllIllI000** [comment]
@hrishibhat agree with sponsor, wrote a test with the provided fields, and changed the signatures too, and the test passed – invalid
