### ISSUE TITLE
hack3r-0m - executing orders might get broken due to console.log

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-gmx-judging#191]
hack3r-0m

medium

# executing orders might get broken due to console.log

## Summary

executing orders might get broken due to console.log

## Vulnerability Detail

`console` lib of hardhat calls a specific address [`0x000000000000000000636F6e736F6c652e6c6f67`](https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat-core/console.sol#L5)  which if has non-zero code then can consume all gas and cause out of gas revert.

this is likely dev enviornment leftover, any untrusted address should not be called in production

## Impact

It can lead to contracts being unusable for that specific path of execution (which is "executing orders" in this case) leading to denial-of-service if that un-trusted address has non-zero bytecode

## Code Snippet

https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/order/IncreaseOrderUtils.sol#L106-L108

## Tool used

Manual Review

## Recommendation

remove `console.log` and replace with emitting event if required.

**Comment by hack3r-0m** [comment]
Escalate for 10 USDC

This should be medium severity under https://docs.sherlock.xyz/audits/judging/judging#how-to-identify-a-medium-issue:
> Causes a loss of funds but requires certain external conditions or specific states.

required condition is mentioned in report

**Comment by IllIllI000** [comment]
It's not possible for someone to deploy a contract to this specific address, as that would require being able to create a `keccak256()` collision. If it were possible, Ethereum security would be broken - Invalid

**Comment by hrishibhat** [comment]
Escalation rejected

Not a valid high/medium issue as shown in the comment above
