### ISSUE TITLE
hack3r-0m - difference in tx.gasPrice is not accounted while paying for execution

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-gmx-judging#200]
hack3r-0m

high

# difference in tx.gasPrice is not accounted while paying for execution

## Summary

for every execution, keeper gets paid `tx.gasPrice` * `estimatedGas` where `tx.gasPrice` can be different while creating action and executing action which can be gamed.

## Vulnerability Detail

let g1 = gasPrice when creating
let g2 = gasPrice when executing / cancelling

diff = (g2 - g1) * estimatedGas
if diff > 0 then keeper looses the difference and if diff < 0 then trader losses that difference by paying extra

## Impact

1) attacker can deplete WNT from vault by creating deposit and then cancelling that deposit at higher gas price since for cancel orders keeper is same as `msg.sender`

2) net loss to keeper when g2 > g1

## Code Snippet

- https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/gas/GasUtils.sol#L50
- https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/deposit/DepositUtils.sol#L192

## Tool used

Manual Review

## Recommendation

adjust for gas price appropriately by 1) charging user at upper bound of gas price 2) adjusting for gas price while refunding user

**Comment by hack3r-0m** [comment]
Escalate for 10 USDC

This should be high severity under https://docs.sherlock.xyz/audits/judging/judging#how-to-identify-a-high-issue:
> Definite loss of funds without limiting external conditions.

for any block where `tx.gasprice` when keeper is execution action is greater than that of when account created transaction, this holds true. And such condtion is very normal and can also be artificially created (for e.g gas price was 135x of normal gas price on arbitrum during airdrop claiming period and this persisted for very long duration)

**Comment by hack3r-0m** [comment]
dup of https://github.com/sherlock-audit/2023-02-gmx-judging/issues/173

**Comment by IllIllI000** [comment]
The gas paid back is [capped](https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/gas/GasUtils.sol#L52-L54) at what was initially provided, so the described attack does not exist. The order submitter gets refunded the unused part of the gas - the keeper doesn't get to take any more than was used. If the user didn't provide enough gas, it's the same as though they submitted the order to a mempool, and it sat in the pool until the gas fees spiked, and eventually ages out.

**Comment by hrishibhat** [comment]
Escalation rejected

Not a valid issue as pointed in the Lead Watson's comment
