### ISSUE TITLE
hack3r-0m - temporary DOS when `cancelOrder` and `executeOrder` features are disabled for a market at same time

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-gmx-judging#202]
hack3r-0m

medium

# temporary DOS when `cancelOrder` and `executeOrder` features are disabled for a market at same time

## Summary

temporary DOS when `cancelOrder` and `executeOrder` features are disabled for a market at same time

## Vulnerability Detail

If there are pending orders to be executed for a market and due to some black swan event if both `cancelOrder` and `executeOrder` features are disabled by admin then user cannot cancel order and get their funds back.

protocol must ensure that whenever execute features are disabled then pending are guaranteed to be enabled for users to claim their funds back from associated vault  since cancelling does not impact accounting of liquidity, position or swap.

## Impact

user cannot claim back funds until either execute feature is enabled is and keeper executes action or cancel feature is enabled and user cancels order successfully

## Code Snippet

- https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/exchange/OrderHandler.sol#L118
- https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/exchange/OrderHandler.sol#L207

## Tool used

Manual Review

## Recommendation

add checks in contract to ensure cancelling is enabled when executing is disabled

**Comment by hack3r-0m** [comment]
Escalate for 10 USDC

under https://docs.sherlock.xyz/audits/judging/judging#how-to-identify-a-medium-issue:
> A material loss of funds, no/minimal profit for the attacker at a considerable cost

here, there is no attacker and hence no profit for attacker
**material loss of funds** is [time value of money](https://www.investopedia.com/terms/t/timevalueofmoney.asp) (i.e due to temporary DOS, user cannot cancel order and obtain their funds back)
