### ISSUE TITLE
simon135 - no checking round data stale and decimals

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-gmx-judging#218]
simon135

medium

# no checking round data stale and decimals

## Summary

no checking round data stale and decimals

## Vulnerability Detail

If chainlink goes down and there is stale pricing of tokens the protocol can be hacked and loss funds

## Impact

can cause loss of funds like if chainlike prices get stale and the decrease of the price of eth is not recorded the protocol will be rewarding eth long users profit when they are not getting profit.

## Code Snippet

```solidity
            (
                ,
                /* uint80 roundID */
                int256 _price,
                ,
                ,

            ) = /* uint256 startedAt */
                /* uint256 timestamp */
                /* uint80 answeredInRound */
                priceFeed.latestRoundData();

```

## Tool used

Manual Review

## Recommendation

```solidity
require(answeredInRound >= roundID, "Chainlink:: Stale price")
require(timestamp > 0, "Chainlink:: Round not complete")
```

**Comment by simonn2** [comment]
Escalate for 10 USDC 
because this issue deals with stale round-data and not validating stale pricing,its dup of  #174

**Comment by IllIllI000** [comment]
Chainlink oracles now use [OCR](https://docs.chain.link/architecture-overview/off-chain-reporting) which has a [single transmitter](https://github.com/sherlock-audit/2022-11-float-capital-judging/issues/4#issuecomment-1319916128) and round checks no longer provide any useful information. While this submission and #174 both point to the same function call, they deal with the processing of different information. This issue does not mention anything at all about old timestamps, and #174 doesn't mention anything at all amout round info, so they are not duplicates

**Comment by hrishibhat** [comment]
Escalation rejected

Not a duplicate of #174 
As shown in the comments check for `answeredInRound` is no longer necessary since the price is returned in a single transaction, the issue also does not provide valid information to consider it a duplicate.
