### ISSUE TITLE
simon135 - we can make this swap fail until we get a minOutput price that is good and make crazy profit by making it a big value

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-gmx-judging#223]
simon135

high

# we can make this swap fail until we get a minOutput price that is good and make crazy profit by making it a big value

## Summary

we can make this swap fail until we get a minOutput price that is good and make a crazy profit
by making it a big value

## Vulnerability Detail
if we specify a huge `minOutput` the tx won't get executed and we can do this to many orders and gain free profit by waiting until the tx is in our favor.
## Impact
free profit or not being able to get liquidate or swap
just like the other issue, I reported the same effect but a different check that is wrong and can cause issues
## Code Snippet
```solidity
        if (outputAmount < params.minOutputAmount) {
            revert InsufficientSwapOutputAmount(outputAmount, params.minOutputAmount);
        }
```
https://github.com/gmx-io/gmx-synthetics/blob/a5f351086f5408be92874851357ea120a9208669/contracts/swap/SwapUtils.sol#L144-L146
## Tool used

Manual Review

## Recommendation
cancel the orders that are not getting executed by the keepers for whatever reason

**Comment by simonn2** [comment]
Escalate for 10 USDC
I think this issue shows an attacker can control when an order happens (because swap happens in the order) and gain free profit. If an attacker just wants to swap and use this attack they can get a free profit swap and when the price is right they make the swap execute (limit order but attacker controlled)

**Comment by IllIllI000** [comment]
Limit orders, both here and in all CEXes, are expected to not execute until the limit has been triggered - Invalid

**Comment by hrishibhat** [comment]
Escalation rejected

Not a valid issue
Agree with the comment above
