### ISSUE TITLE
hack3r-0m - callback receiver can control when to allow order execution

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-gmx-judging#231]
hack3r-0m

high

# callback receiver can control when to allow order execution

## Summary

callback receiver can control when to allow order execution

## Vulnerability Detail

```solidity
        uint256 marketTokensBalance = MarketToken(payable(withdrawal.market())).balanceOf(withdrawal.account());
        if (marketTokensBalance < withdrawal.marketTokenAmount()) {
            revert InsufficientMarketTokens(marketTokensBalance, withdrawal.marketTokenAmount());
        }
```     
this allow attackers to have control over when it will not be reverted, attacker will increase upto required balance to and delay withdrawal to benifit from fees or market movement until that 

## Impact

unintended access control for when to allow withdrawal

## Code Snippet

https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/deposit/ExecuteDepositUtils.sol#L392

## Tool used

Manual Review

## Recommendation

do not use balanceOf checks, instead revert and consume all gas on failed transfer

**Comment by hack3r-0m** [comment]
Escalate for 10 USDC
here, the callback receiver can control value `balanceOf(marketToken)` (practically, by transfering to some other address then itself and so check fails and withdrawal doesn't execute) which allows risk free trade.

the code snippet in "Vulnerability Detail" is the correct one i wanted to mention while location on code snippet location should be https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/withdrawal/WithdrawalUtils.sol#L195 , apologies in case judges were not to find that and marked issue excluded

**Comment by IllIllI000** [comment]
executeWithdrawal(), which [throws](https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/withdrawal/WithdrawalUtils.sol#L197) the error, is called by [_executeWithdrawal()](https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/exchange/WithdrawalHandler.sol#L175), which, if it [throws an exception](https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/exchange/WithdrawalHandler.sol#L109), will [cancel the order](https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/exchange/WithdrawalHandler.sol#L191) - Invalid

**Comment by hrishibhat** [comment]
Escalation rejected

Based on the comments above there is no valid issue here
