### ISSUE TITLE
simon135 - An attacker can control when the withdraw happens of market tokens and get better price

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-gmx-judging#232]
simon135

high

# An attacker can control when the withdraw happens of market tokens and get better price

## Summary
An attacker can control when the withdrawal happens of market tokens and get a better price by sending funds to another account.
## Vulnerability Detail
There is a check in the `withdrawUtils` contract that specifies that the account must have the balance of market tokens they want to withdraw.
An attacker can control when their withdrawal happens by  sending funds to another account before the keepers make the tx and it will not get executed then when the attacker wants the withdrawal to happen they will send the market tokens back
ex:
1. Alice  creates a request for withdrawal with 50 markets tokens and their account has 50 market tokens
2.  keeper sends the tx in mempool  for executing the withdraw 
3. Alice front runs and sends 25 market tokens to another attacker-controlled address  (because alice would only get back 50 eth)
4. keeper won't execute the tx
some time passes
5. Alice transfers back 25 market tokens to account and now the withdraw can be executed 
6. Keeper executes the tx and Alice gets 100 eth making 50 eth profit 
## Impact
Free profit and the attacker can control when to withdraw gets executed that is an issue in itself  
## Code Snippet
```solidity
       if (marketTokensBalance < withdrawal.marketTokenAmount()) {
            revert InsufficientMarketTokens(marketTokensBalance, withdrawal.marketTokenAmount());
        }
```

## Tool used

Manual Review

## Recommendation
make keeper use flashbots

**Comment by simonn2** [comment]
Escalate for 10 USDC
dup of https://github.com/sherlock-audit/2023-02-gmx-judging/issues/231

**Comment by IllIllI000** [comment]
This finding is indeed a duplicate of #231, but 231 is invalid, and therefore so is this one - Invalid

**Comment by hrishibhat** [comment]
Escalation accepted

Valid duplicate of #231
