### ISSUE TITLE
koxuan - applySwapImpactWithCap is too harsh and unnecessarily reduces user positive price impact reward

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-gmx-judging#44]
koxuan

medium

# applySwapImpactWithCap is too harsh and unnecessarily reduces user positive price impact reward

## Summary
When there is a positive price impact when depositing (initial pool value difference between long and short token < next pool value difference between long and short token), depositor will be rewarded with the positive price impact amount. However, when capping the positive swap impact that user can be rewarded based on impact pool amount, positive price impact is unnecessarily diluted from calculation.   

## Vulnerability Detail
In `executeDeposit`, `positiveImpactAmount` will be calculated by `applySwapImpactWithCap` function for the `_params.priceImpactUsd`. positiveImpactAmount is then multiplied by min price to determine mint amount.
```solidity
            int256 positiveImpactAmount = MarketUtils.applySwapImpactWithCap(
                params.dataStore,
                params.eventEmitter,
                _params.market.marketToken,
                _params.tokenOut,
                _params.tokenOutPrice,
                _params.priceImpactUsd
            );


            // calculate the usd amount using positiveImpactAmount since it may
            // be capped by the max available amount in the impact pool
            mintAmount += MarketUtils.usdToMarketTokenAmount(
                positiveImpactAmount.toUint256() * _params.tokenOutPrice.min,
                poolValue,
                supply
            );
```

However, in `applySwapImpactWithCap`, notice that when there is a positive price impact, `tokenPrice.max` is used instead to determine the impactAmount. The `applySwapImpactWithCap` purpose is to cap price impact to available funds in impact pool, but this calculation to determine whether to cap or not will cause positive price impact amount to decrease unnecessarily for depositor. Imagine a situation where a deposit has a positive price impact that the impact pool can cover, but after the divide by tokenPrice.max and multiplication by tokenPrice.min, the deposit's positive price impact will decrease for no reason.

```solidity
        // positive impact: minimize impactAmount, use tokenPrice.max
        // negative impact: maximize impactAmount, use tokenPrice.min
        uint256 price = priceImpactUsd > 0 ? tokenPrice.max : tokenPrice.min;


        int256 impactAmount;


        if (priceImpactUsd > 0) {
            // round positive impactAmount down, this will be deducted from the swap impact pool for the user
            impactAmount = priceImpactUsd / price.toInt256();
```
## Impact
Unnecessary loss to positive price impact reward.

## Code Snippet
[ExecuteDepositUtils.sol#L308-L323](https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/deposit/ExecuteDepositUtils.sol#L308-L323)

[MarketUtils.sol#L1190-L1198](https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/market/MarketUtils.sol#L1190-L1198)
## Tool used

Manual Review

## Recommendation

Recommend using _params.priceImpactUsd as input for mint amount calculation if impact pool can cover user positive price impact.

**Comment by xvi10** [comment]
this is a valid concern, but we feel it is safer to use the more aggressive cap for this calculation
