### ISSUE TITLE
bearonbike - EOA could have Controller role, but it shouldn't.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-gmx-judging#46]
bearonbike

medium

# EOA could have Controller role, but it shouldn't.

## Summary
RoleAdmin could grant EOA a Controller role, but it shouldn't.

## Vulnerability Detail
According to README L418: 
https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/README.md?plain=1#L418
But actually after inital setup, Timelock(RoleAdmin) could malicously/negligently grant an EOA Controller role.
Controller role have many authorities, such as transfer funds out of Bank, update token transfer record etc. If Controller role is granted to a malicious EOA, funds could be drained.

## Impact
Controller role could be granted to malicious EOA, lead to capital loss.

## Code Snippet
https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/config/Timelock.sol#L109-L123
https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/config/Timelock.sol#L128-L144
https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/role/RoleStore.sol#L47-L49
https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/role/RoleStore.sol#L114-L118

## Tool used

Manual Review

## Recommendation
Consider constrain account is not EOA when roleKey is Controller role in Timelock.signalGrantRole function.

**Comment by IllIllI000** [comment]
Sherlock does not reward [admin errors](https://docs.sherlock.xyz/audits/judging/judging#list-of-issue-categories-that-are-not-considered-valid), and no funds are at risk

**Comment by hrishibhat** [comment]
Escalation rejected

Since the roleAdmin is trusted to assign roles this is not a valid issue.
