### ISSUE TITLE
Laksmana - operator error in ``setPrices`` function (contract Oracle.sol)

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-gmx-judging#66]
Laksmana

high

# operator error in ``setPrices`` function (contract Oracle.sol)

## Summary
The operator `!=` has higher precedence than the operator `&` 
reference:
https://github.com/ethereum/solidity/issues/13831
## Vulnerability Detail
```solidity
function setPrices(
        DataStore dataStore,
        EventEmitter eventEmitter,
        OracleUtils.SetPricesParams memory params
    ) external onlyController {
        if (tokensWithPrices.length() != 0) {
            revert NonEmptyTokensWithPrices(tokensWithPrices.length());
        }

        if (params.tokens.length == 0) { revert EmptyTokens(); }

        // first 16 bits of signer info contains the number of signers
        address[] memory signers = new address[](params.signerInfo & Bits.BITMASK_16);

        if (signers.length < dataStore.getUint(Keys.MIN_ORACLE_SIGNERS)) {
            revert MinOracleSigners(signers.length, dataStore.getUint(Keys.MIN_ORACLE_SIGNERS));
        }

        if (signers.length > MAX_SIGNERS) {
            revert MaxOracleSigners(signers.length, MAX_SIGNERS);
        }

        uint256 signerIndexFlags;

        for (uint256 i = 0; i < signers.length; i++) {
            uint256 signerIndex = params.signerInfo >> (16 + 16 * i) & Bits.BITMASK_16;

            if (signerIndex >= MAX_SIGNER_INDEX) {
                revert MaxSignerIndex(signerIndex, MAX_SIGNER_INDEX);
            }

            uint256 signerIndexBit = 1 << signerIndex;

            if (signerIndexFlags & signerIndexBit != 0) {
                revert DuplicateSigner(signerIndex);
            }

            signerIndexFlags = signerIndexFlags | signerIndexBit;

            signers[i] = oracleStore.getSigner(signerIndex);
        }

        _setPrices(
            dataStore,
            eventEmitter,
            signers,
            params
        );

        _setPricesFromPriceFeeds(dataStore, eventEmitter, params.priceFeedTokens);
    }
```
see the code above the statement `if` on line 44:
```solidity 
 if (signerIndexFlags & signerIndexBit != 0) {
                revert DuplicateSigner(signerIndex);
            }
```
The `&` and `!=` operators have different precedence levels, where `&` has lower precedence than `!=`. Therefore, the `signerIndexBit` operation will be evaluated first using the `!=` operator.

For example, if `signerIndexFlags` is equal to 2 and `signerIndexBit` is equal to 1, then the `signerIndexFlags & signerIndexBit` operation will result in a value of 0, meaning that there are no matching bits between `signerIndexFlags` and `signerIndexBit`. 

However, because the `!=` operator has higher precedence than the `&` operator, the condition inside the parentheses will be evaluated as `(signerIndexFlags & (signerIndexBit != 0)) != 0`, which is always true because `(signerIndexBit != 0)` will always be true, and the result of the bitwise `&` operation will always be the same as `signerIndexBit`.

## Impact
this operator doesn't work
```solidity
if (signerIndexFlags & signerIndexBit != 0) {
                revert DuplicateSigner(signerIndex);
            }
```
so that the Signer(signerIndex) can be duplicated
## Code Snippet
https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/oracle/Oracle.sol#L244-L246
## Tool used

Manual Review

## Recommendation
change the the code like this 
```solidity
if ((signerIndexFlags & signerIndexBit) != 0) {
    revert DuplicateSigner(signerIndex);
}
```

**Comment by PutraLaksmana** [comment]
It's a bug 
See this : https://github.com/ethereum/solidity/issues/13831

**Comment by PutraLaksmana** [comment]
Escalate for 10 USDC. See the problem here: https://github.com/ethereum/solidity/issues/13831

**Comment by PutraLaksmana** [comment]
Full explanation here : https://github.com/ethereum/solidity/issues/13831

**Comment by IllIllI000** [comment]
The issue you link to says that the submitted issue is [invalid](https://github.com/ethereum/solidity/issues/13831#issuecomment-1366788694). This test case also shows that there is no problem:
```solidity
pragma solidity 0.8.17;

import "forge-std/Test.sol";

contract It is Test {
    function testIt(uint256 signerIndexFlags, uint256 signerIndexBit) external view returns (uint256) {
        bool origResult = (signerIndexFlags & signerIndexBit != 0);
	bool newResult  = ((signerIndexFlags & signerIndexBit) != 0);
	assert(origResult == newResult);
	return 0;
    }
}
```
Invalid

**Comment by hrishibhat** [comment]
Escalation rejected

Not a valid issue
