### ISSUE TITLE
rvierdiiev - Price impact is not calculated for initial market when withdrawing

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-gmx-judging#69]
rvierdiiev

high

# Price impact is not calculated for initial market when withdrawing

## Summary
Price impact is not calculated for initial market when withdrawing
## Vulnerability Detail
When user deposits some initialShortToken and initialLongToken, then this tokens are going to [be swapped](https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/deposit/ExecuteDepositUtils.sol#L129-L145) to the market long/short tokens, were user wants to mint LP tokens.
Along the swaps, for each swap [price impact is calculated and accrued](https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/swap/SwapUtils.sol#L184-L238). After that, when initial tokens are swapped to market.longToken/shortToken, impact price [is calculated](https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/deposit/ExecuteDepositUtils.sol#L179-L190) and [accrued](https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/deposit/ExecuteDepositUtils.sol#L297-L348) for the market, were LP will be minted.

But when user withdraws, then price impact for current market [is not calculated and not accrued](https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/withdrawal/WithdrawalUtils.sol#L261-L391). But price impact will be calculated during the swap from market.longToken/shortToken to the output tokens. 

This is incorrect. For example if user will initiate withdraw without exchanging market.LongToken/shortToken to another tokens, then no price impact will be calculated at all.
## Impact
Price impact is not calculated and accrued for withdrawal market. Increase risk of price manipulation.
## Code Snippet
Provided above
## Tool used

Manual Review

## Recommendation
You need to calculate price impact of withdrawing for initial market.

**Comment by xvi10** [comment]
for withdrawals, long and short token are withdrawn in equal USD amounts, so there is no price impact

**Comment by IllIllI000** [comment]
I believe the sponsor was just being imprecise in the description. The amounts aren't equal, but the ratios of the amounts withdrawn make it so that there is no price impact. In your example the long/short ratio was `60/40=1.5`, and after the change it was still `48/32=1.5` as long as the ratio is the same, there is no price impact

**Comment by xvi10** [comment]
yes, sorry that the original comment was not precise, the change in USD balance between the long and short tokens should not change due to the withdrawal, so there should not be a price impact aside from swaps

**Comment by hrishibhat** [comment]
Escalation rejected 

As shown from the above comments that the ratio remains the same, there is no price impact.
Issue is not a valid high/medium
